### ISSUE TITLE
error ModuleNotFoundError: No module named 'quality_prompts.prompt'; 'quality_prompts' is not a package

### ISSUE THREAD

**Issue by therealtimex** [sarthakrastogi/quality-prompts#3]
I pip install successfully, but I encounter this error:

ModuleNotFoundError: No module named 'quality_prompts.prompt'; 'quality_prompts' is not a package

Any idea how I can get around it?

**Comment by sarthakrastogi** [comment]
Did you install in the same environment in which you are accessing the module?

**Comment by therealtimex** [comment]
Yes, absolutely.
